-- 插入默认角色数据
INSERT INTO sys_role (ROLE_ID, ROLE_CODE, ROLE_NAME, ROLE_DESC, ROLE_TYPE, ROLE_STATUS, DELETE_MARK)
VALUES (1, 'AI_ADMIN', 'AI项目管理员', 'AI项目管理员角色', 'SYSTEM', 'ACTIVE', '0')
ON DUPLICATE KEY UPDATE
  ROLE_NAME = 'AI项目管理员',
  ROLE_DESC = 'AI项目管理员角色';
